/**
 * YouTube subtitle adapter.
 * Fetches and normalizes YouTube subtitles to Cue format.
 */

import type { Cue } from '@lexipath/core';

export interface YouTubeSubtitleTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export class YouTubeAdapter {
  /**
   * Get available subtitle tracks for a video.
   */
  async getAvailableTracks(_videoId: string): Promise<YouTubeSubtitleTrack[]> {
    // TODO: Implement subtitle track discovery
    return [];
  }

  /**
   * Fetch subtitles for a specific track.
   */
  async fetchSubtitles(_videoId: string, _languageCode: string): Promise<Cue[]> {
    // TODO: Implement subtitle fetching
    return [];
  }
}
