import { afterEach, describe, expect, it, vi } from 'vitest';
import { fetchSubtitles, getAvailableTracks, getVideoId } from './index';

afterEach(() => {
  vi.unstubAllGlobals();
  vi.resetAllMocks();
});

describe('getVideoId', () => {
  it('extracts id from watch URL', () => {
    expect(getVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts id from youtu.be short URL', () => {
    expect(getVideoId('https://youtu.be/dQw4w9WgXcQ?t=43')).toBe('dQw4w9WgXcQ');
  });

  it('extracts id from shorts URL', () => {
    expect(getVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ?feature=share')).toBe(
      'dQw4w9WgXcQ'
    );
  });

  it('extracts id from embed URL', () => {
    expect(getVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('returns id when input is already a video id', () => {
    expect(getVideoId('dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('returns null for invalid input', () => {
    expect(getVideoId('https://example.com')).toBeNull();
  });
});

describe('getAvailableTracks', () => {
  it('extracts captionTracks from watch HTML and returns simplified tracks', async () => {
    const videoId = 'dQw4w9WgXcQ';
    const html = `... "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en","name":{"runs":[{"text":"English"}]},"languageCode":"en"},
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr","name":{"simpleText":"English (auto)"},"languageCode":"en","kind":"asr"},
      {"baseUrl":"//www.youtube.com/api/timedtext?v=${videoId}&lang=ja","name":"日本語","languageCode":"ja"}
    ]}},"videoDetails"...`;

    const fetchMock = vi.fn(async (_input: RequestInfo | URL, _init?: RequestInit) => {
      return new Response(html, { status: 200, headers: { 'content-type': 'text/html' } });
    });
    vi.stubGlobal('fetch', fetchMock);

    await expect(getAvailableTracks(videoId)).resolves.toEqual([
      { languageCode: 'en', name: 'English', isAutoGenerated: false },
      { languageCode: 'en', name: 'English (auto)', isAutoGenerated: true },
      { languageCode: 'ja', name: '日本語', isAutoGenerated: false },
    ]);

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(String(fetchMock.mock.calls[0]?.[0])).toContain(`youtube.com/watch?v=${videoId}`);
  });
});

describe('fetchSubtitles', () => {
  it('prefers manual track by default and parses json3 timedtext events into cues', async () => {
    const videoId = 'dQw4w9WgXcQ';
    const html = `... "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en","name":{"simpleText":"English"},"languageCode":"en"},
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr","name":{"simpleText":"English (auto)"},"languageCode":"en","kind":"asr"}
    ]}},"videoDetails"...`;

    const fetchMock = vi.fn(async (input: RequestInfo | URL, _init?: RequestInit) => {
      const url = String(input);
      if (url.includes('youtube.com/watch')) {
        return new Response(html, { status: 200, headers: { 'content-type': 'text/html' } });
      }

      if (url.includes('/api/timedtext')) {
        return new Response(
          JSON.stringify({
            events: [
              {
                tStartMs: 0,
                dDurationMs: 1500,
                segs: [{ utf8: 'Hello' }, { utf8: 'world' }],
              },
              { tStartMs: 1500, dDurationMs: 0, segs: [{ utf8: 'invalid' }] },
            ],
          }),
          { status: 200, headers: { 'content-type': 'application/json' } }
        );
      }

      return new Response('unexpected url', { status: 500 });
    });
    vi.stubGlobal('fetch', fetchMock);

    const cues = await fetchSubtitles(videoId, 'en');
    expect(cues).toEqual([
      {
        id: `youtube:${videoId}:0-1500:0`,
        startMs: 0,
        endMs: 1500,
        text: 'Hello world',
        lang: 'en',
        source: 'youtube',
      },
    ]);

    expect(fetchMock).toHaveBeenCalledTimes(2);
    const timedTextUrl = String(fetchMock.mock.calls[1]?.[0]);
    expect(timedTextUrl).toContain('fmt=json3');
    expect(timedTextUrl).not.toContain('kind=asr');
  });

  it('can select auto-generated track explicitly via :auto suffix', async () => {
    const videoId = 'dQw4w9WgXcQ';
    const html = `... "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en","name":{"simpleText":"English"},"languageCode":"en"},
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr","name":{"simpleText":"English (auto)"},"languageCode":"en","kind":"asr"}
    ]}},"videoDetails"...`;

    const fetchMock = vi.fn(async (input: RequestInfo | URL, _init?: RequestInit) => {
      const url = String(input);
      if (url.includes('youtube.com/watch')) {
        return new Response(html, { status: 200, headers: { 'content-type': 'text/html' } });
      }

      if (url.includes('/api/timedtext')) {
        return new Response(
          JSON.stringify({
            events: [
              {
                tStartMs: 100,
                dDurationMs: 900,
                segs: [{ utf8: 'Auto' }],
              },
            ],
          }),
          { status: 200, headers: { 'content-type': 'application/json' } }
        );
      }

      return new Response('unexpected url', { status: 500 });
    });
    vi.stubGlobal('fetch', fetchMock);

    const cues = await fetchSubtitles(videoId, 'en:auto');
    expect(cues[0]?.text).toBe('Auto');

    const timedTextUrl = String(fetchMock.mock.calls[1]?.[0]);
    expect(timedTextUrl).toContain('kind=asr');
  });

  it('falls back to XML parsing when timedtext response is not json', async () => {
    const videoId = 'dQw4w9WgXcQ';
    const html = `... "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
      {"baseUrl":"https://www.youtube.com/api/timedtext?v=${videoId}&lang=en","name":{"simpleText":"English"},"languageCode":"en"}
    ]}},"videoDetails"...`;

    const xml = `<transcript><text start="0.5" dur="1.0">Hello &amp; world</text></transcript>`;

    const fetchMock = vi.fn(async (input: RequestInfo | URL, _init?: RequestInit) => {
      const url = String(input);
      if (url.includes('youtube.com/watch')) {
        return new Response(html, { status: 200, headers: { 'content-type': 'text/html' } });
      }
      if (url.includes('/api/timedtext')) {
        return new Response(xml, { status: 200, headers: { 'content-type': 'text/xml' } });
      }
      return new Response('unexpected url', { status: 500 });
    });
    vi.stubGlobal('fetch', fetchMock);

    await expect(fetchSubtitles(videoId, 'en')).resolves.toEqual([
      {
        id: `youtube:${videoId}:500-1500:0`,
        startMs: 500,
        endMs: 1500,
        text: 'Hello & world',
        lang: 'en',
        source: 'youtube',
      },
    ]);
  });
});

