/**
 * YouTube subtitle adapter.
 * Fetches and normalizes YouTube subtitles to Cue format.
 */

import type { Cue } from '@lexipath/core';
import { z } from 'zod';

export interface YouTubeSubtitleTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

type YouTubeCaptionTrack = {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
};

function normalizeYouTubeUrl(url: string): string {
  const trimmed = url.trim();
  if (!trimmed) return trimmed;
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) return trimmed;
  if (trimmed.startsWith('//')) return `https:${trimmed}`;
  if (trimmed.startsWith('/')) return `https://www.youtube.com${trimmed}`;
  return trimmed;
}

function isValidVideoId(candidate: string): boolean {
  return /^[0-9A-Za-z_-]{11}$/.test(candidate);
}

/**
 * Extract YouTube video id from various URL shapes:
 * - https://www.youtube.com/watch?v=VIDEO_ID
 * - https://youtu.be/VIDEO_ID
 * - https://www.youtube.com/shorts/VIDEO_ID
 * - https://www.youtube.com/embed/VIDEO_ID
 */
export function getVideoId(url: string): string | null {
  const raw = url.trim();
  if (!raw) return null;
  if (isValidVideoId(raw)) return raw;

  const extractFromPath = (pathname: string): string | null => {
    const match = pathname.match(/\/(shorts|embed|v|live)\/([0-9A-Za-z_-]{11})/);
    return match?.[2] ?? null;
  };

  try {
    const parsed = new URL(raw);
    const host = parsed.hostname.toLowerCase();

    const v = parsed.searchParams.get('v');
    if (v && isValidVideoId(v)) return v;

    if (host === 'youtu.be' || host.endsWith('.youtu.be')) {
      const id = parsed.pathname.split('/').filter(Boolean)[0] ?? '';
      if (isValidVideoId(id)) return id;
    }

    const fromPath = extractFromPath(parsed.pathname);
    if (fromPath) return fromPath;

    const u = parsed.searchParams.get('u');
    if (u) {
      try {
        const decoded = decodeURIComponent(u);
        const asUrl = decoded.startsWith('http') ? decoded : `https://www.youtube.com${decoded}`;
        return getVideoId(asUrl);
      } catch {
        // ignore
      }
    }
  } catch {
    // Not an absolute URL; fall through to regex parsing.
  }

  const match = raw.match(/\b([0-9A-Za-z_-]{11})\b/);
  return match?.[1] && isValidVideoId(match[1]) ? match[1] : null;
}

function extractJsonValue(html: string, startIndex: number): string | null {
  const open = html[startIndex];
  if (open !== '{' && open !== '[') return null;

  const stack: Array<'{' | '['> = [];
  let inString = false;
  let escaped = false;

  for (let i = startIndex; i < html.length; i++) {
    const char = html[i];
    if (!char) continue;

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }
      if (char === '\\') {
        escaped = true;
        continue;
      }
      if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === '{' || char === '[') {
      stack.push(char);
      continue;
    }

    if (char === '}' || char === ']') {
      const last = stack[stack.length - 1];
      if (!last) return null;

      if ((char === '}' && last !== '{') || (char === ']' && last !== '[')) {
        return null;
      }

      stack.pop();
      if (stack.length === 0) {
        return html.slice(startIndex, i + 1);
      }
    }
  }

  return null;
}

function findJsonValueAfterKey(html: string, key: string): string | null {
  let index = html.indexOf(key);
  while (index !== -1) {
    const colonIndex = html.indexOf(':', index + key.length);
    if (colonIndex === -1) return null;

    for (let i = colonIndex + 1; i < html.length; i++) {
      const char = html[i];
      if (!char) continue;
      if (char === ' ' || char === '\n' || char === '\r' || char === '\t') continue;
      if (char !== '{' && char !== '[') break;
      return extractJsonValue(html, i);
    }

    index = html.indexOf(key, index + key.length);
  }

  return null;
}

const CaptionTrackNameSchema = z.union([
  z.string(),
  z.object({
    simpleText: z.string().optional(),
    runs: z
      .array(
        z.object({
          text: z.string(),
        })
      )
      .optional(),
  }),
]);

const CaptionTrackSchema = z.object({
  baseUrl: z.string(),
  languageCode: z.string(),
  name: CaptionTrackNameSchema.optional(),
  kind: z.string().optional(),
  vssId: z.string().optional(),
});
type CaptionTrackParsed = z.infer<typeof CaptionTrackSchema>;

function getTrackName(track: CaptionTrackParsed): string {
  const raw = track.name;
  if (!raw) return track.languageCode;
  if (typeof raw === 'string') return raw;
  if (raw.simpleText) return raw.simpleText;
  const runs = raw.runs ?? [];
  const joined = runs.map((r) => r.text).join('');
  return joined || track.languageCode;
}

function isAutoGeneratedTrack(track: CaptionTrackParsed): boolean {
  const kind = track.kind?.toLowerCase();
  if (kind === 'asr') return true;
  return track.vssId?.startsWith('a.') ?? false;
}

function parseCaptionTracksFromWatchHtml(html: string): YouTubeCaptionTrack[] {
  const captionTracksJson =
    findJsonValueAfterKey(html, '"captionTracks"') ??
    findJsonValueAfterKey(html, '"playerCaptionsTracklistRenderer"') ??
    findJsonValueAfterKey(html, '"captions"');

  if (!captionTracksJson) return [];

  let parsedUnknown: unknown;
  try {
    parsedUnknown = JSON.parse(captionTracksJson) as unknown;
  } catch {
    return [];
  }

  const candidateArray =
    (Array.isArray(parsedUnknown) && parsedUnknown) ||
    (typeof parsedUnknown === 'object' && parsedUnknown !== null
      ? (() => {
          const asRecord = parsedUnknown as Record<string, unknown>;
          const asTracklist =
            (asRecord.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined) ??
            (asRecord.captionTracks as Record<string, unknown> | undefined);
          if (asTracklist && typeof asTracklist === 'object') {
            const tracks = (asTracklist as Record<string, unknown>).captionTracks;
            if (Array.isArray(tracks)) return tracks;
          }
          const tracks = asRecord.captionTracks;
          if (Array.isArray(tracks)) return tracks;
          return null;
        })()
      : null);

  if (!candidateArray) return [];

  return candidateArray
    .map((raw): YouTubeCaptionTrack | null => {
      const parsed = CaptionTrackSchema.safeParse(raw);
      if (!parsed.success) return null;

      const baseUrl = normalizeYouTubeUrl(parsed.data.baseUrl);
      if (!baseUrl) return null;

      return {
        baseUrl,
        languageCode: parsed.data.languageCode,
        name: getTrackName(parsed.data),
        isAutoGenerated: isAutoGeneratedTrack(parsed.data),
      };
    })
    .filter((track): track is YouTubeCaptionTrack => track !== null);
}

async function fetchYouTubeWatchHtml(videoId: string): Promise<string> {
  const url = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`;
  const response = await fetch(url, {
    method: 'GET',
    headers: { Accept: 'text/html,*/*' },
  });

  if (!response.ok) {
    throw new Error(`YouTube watch fetch failed: HTTP ${response.status} ${response.statusText}`);
  }

  return response.text();
}

async function getCaptionTracks(videoId: string): Promise<YouTubeCaptionTrack[]> {
  const html = await fetchYouTubeWatchHtml(videoId);
  return parseCaptionTracksFromWatchHtml(html);
}

type LangPreference = {
  lang: string;
  preferAuto: boolean | null;
};

function normalizeLang(lang: string): string {
  return lang.trim().replace(/_/g, '-').toLowerCase();
}

function parseLangPreference(lang: string): LangPreference {
  const raw = lang.trim();
  if (!raw) return { lang: '', preferAuto: null };

  const normalized = raw.replace(/_/g, '-');

  const colonParts = normalized.split(':');
  if (colonParts.length >= 2) {
    const suffix = colonParts[colonParts.length - 1]?.toLowerCase();
    const base = colonParts.slice(0, -1).join(':').trim();
    if (!suffix || !base) return { lang: normalizeLang(normalized), preferAuto: null };
    if (suffix === 'auto' || suffix === 'asr') return { lang: normalizeLang(base), preferAuto: true };
    if (suffix === 'manual') return { lang: normalizeLang(base), preferAuto: false };
  }

  const lowered = normalized.toLowerCase();
  if (lowered.endsWith('-auto') || lowered.endsWith('-asr')) {
    return { lang: normalizeLang(normalized.replace(/-(auto|asr)$/i, '')), preferAuto: true };
  }
  if (lowered.endsWith('-manual')) {
    return { lang: normalizeLang(normalized.replace(/-manual$/i, '')), preferAuto: false };
  }

  return { lang: normalizeLang(normalized), preferAuto: null };
}

function languageMatches(trackLanguage: string, requestedLanguage: string): boolean {
  const track = normalizeLang(trackLanguage);
  const requested = normalizeLang(requestedLanguage);
  if (!track || !requested) return false;
  if (track === requested) return true;
  if (track.startsWith(`${requested}-`)) return true;
  if (requested.startsWith(`${track}-`)) return true;
  return false;
}

function pickCaptionTrack(
  tracks: YouTubeCaptionTrack[],
  requestedLang: string
): YouTubeCaptionTrack | null {
  const pref = parseLangPreference(requestedLang);
  const candidates = tracks.filter((t) => languageMatches(t.languageCode, pref.lang));
  if (candidates.length === 0) return null;

  const wantAuto = pref.preferAuto;

  const score = (track: YouTubeCaptionTrack): number => {
    const exact = normalizeLang(track.languageCode) === pref.lang ? 0 : 10;
    const autoPenalty =
      wantAuto === true ? (track.isAutoGenerated ? 0 : 2) : wantAuto === false ? (track.isAutoGenerated ? 2 : 0) : track.isAutoGenerated ? 1 : 0;
    const specificity = Math.abs(normalizeLang(track.languageCode).length - pref.lang.length);
    return exact + autoPenalty + specificity / 100;
  };

  return candidates.slice().sort((a, b) => score(a) - score(b))[0] ?? null;
}

function decodeHtmlEntities(input: string): string {
  const withBreaks = input.replace(/<br\s*\/?>/gi, '\n');

  const named: Record<string, string> = {
    amp: '&',
    lt: '<',
    gt: '>',
    quot: '"',
    apos: "'",
    nbsp: '\u00A0',
  };

  return withBreaks.replace(/&(#x[0-9a-fA-F]+|#\d+|[a-zA-Z]+);/g, (match, entity) => {
    if (entity[0] === '#') {
      const isHex = entity[1]?.toLowerCase() === 'x';
      const numeric = isHex ? entity.slice(2) : entity.slice(1);
      const codePoint = Number.parseInt(numeric, isHex ? 16 : 10);
      if (Number.isFinite(codePoint) && codePoint >= 0) {
        try {
          return String.fromCodePoint(codePoint);
        } catch {
          return match;
        }
      }
      return match;
    }

    return named[entity] ?? match;
  });
}

function normalizeCueText(text: string): string {
  const withBreaks = text.replace(/<br\s*\/?>/gi, '\n');
  const noTags = withBreaks.replace(/<\/?[^>]+>/g, '');
  const decoded = decodeHtmlEntities(noTags);
  const lines = decoded
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trim().replace(/\s+/g, ' '))
    .filter(Boolean);
  return lines.join('\n').trim();
}

const TimedTextJson3Schema = z.object({
  events: z
    .array(
      z.object({
        tStartMs: z.number().optional(),
        dDurationMs: z.number().optional(),
        segs: z
          .array(
            z.object({
              utf8: z.string().optional(),
            })
          )
          .optional(),
      })
    )
    .optional(),
});

export function youtubeTimedTextToCues(
  timedText: unknown,
  options: { videoId: string; lang: string }
): Cue[] {
  if (typeof timedText === 'string') {
    return youtubeTimedTextXmlToCues(timedText, options);
  }

  const jsonParsed = TimedTextJson3Schema.safeParse(timedText);
  if (jsonParsed.success) {
    return youtubeTimedTextJson3ToCues(jsonParsed.data, options);
  }

  return [];
}

function youtubeTimedTextJson3ToCues(
  timedText: z.infer<typeof TimedTextJson3Schema>,
  options: { videoId: string; lang: string }
): Cue[] {
  const events = timedText.events ?? [];
  const lang = options.lang || 'und';

  return events
    .map((event, index): Cue | null => {
      const startMs = event.tStartMs;
      const durationMs = event.dDurationMs;
      if (startMs === undefined || durationMs === undefined) return null;

      const endMs = startMs + durationMs;
      if (!Number.isFinite(startMs) || !Number.isFinite(endMs)) return null;
      if (endMs <= startMs) return null;

      const segs = event.segs ?? [];
      const text = normalizeCueText(
        segs
          .map((s) => s.utf8 ?? '')
          .filter((s) => s.trim())
          .join(' ')
      );
      if (!text) return null;

      return {
        id: `youtube:${options.videoId}:${startMs}-${endMs}:${index}`,
        startMs,
        endMs,
        text,
        lang,
        source: 'youtube',
      };
    })
    .filter((cue): cue is Cue => cue !== null);
}

function youtubeTimedTextXmlToCues(xml: string, options: { videoId: string; lang: string }): Cue[] {
  const lang = options.lang || 'und';

  const parseTranscript = (): Cue[] => {
    const cues: Cue[] = [];
    const regex = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
    let match: RegExpExecArray | null;
    let index = 0;

    while ((match = regex.exec(xml)) !== null) {
      const attrs = match[1] ?? '';
      const content = match[2] ?? '';
      const startMatch = attrs.match(/\bstart="([^"]+)"/);
      const durMatch = attrs.match(/\bdur="([^"]+)"/);
      const startSeconds = startMatch?.[1] ? Number.parseFloat(startMatch[1]) : Number.NaN;
      const durSeconds = durMatch?.[1] ? Number.parseFloat(durMatch[1]) : Number.NaN;
      if (!Number.isFinite(startSeconds) || !Number.isFinite(durSeconds)) continue;

      const startMs = Math.round(startSeconds * 1000);
      const endMs = Math.round((startSeconds + durSeconds) * 1000);
      if (endMs <= startMs) continue;

      const text = normalizeCueText(content);
      if (!text) continue;

      cues.push({
        id: `youtube:${options.videoId}:${startMs}-${endMs}:${index}`,
        startMs,
        endMs,
        text,
        lang,
        source: 'youtube',
      });
      index++;
    }

    return cues;
  };

  const parseSrv3 = (): Cue[] => {
    const cues: Cue[] = [];
    const regex = /<p\b([^>]*)>([\s\S]*?)<\/p>/g;
    let match: RegExpExecArray | null;
    let index = 0;

    while ((match = regex.exec(xml)) !== null) {
      const attrs = match[1] ?? '';
      const content = match[2] ?? '';
      const tMatch = attrs.match(/\bt="([^"]+)"/);
      const dMatch = attrs.match(/\bd="([^"]+)"/);
      const startMs = tMatch?.[1] ? Number.parseInt(tMatch[1], 10) : Number.NaN;
      const durationMs = dMatch?.[1] ? Number.parseInt(dMatch[1], 10) : Number.NaN;
      if (!Number.isFinite(startMs) || !Number.isFinite(durationMs)) continue;
      const endMs = startMs + durationMs;
      if (endMs <= startMs) continue;

      const text = normalizeCueText(content);
      if (!text) continue;

      cues.push({
        id: `youtube:${options.videoId}:${startMs}-${endMs}:${index}`,
        startMs,
        endMs,
        text,
        lang,
        source: 'youtube',
      });
      index++;
    }

    return cues;
  };

  const hasP = xml.includes('<p') && xml.includes(' t="') && xml.includes(' d="');
  const hasText = xml.includes('<text') && xml.includes(' start="');

  if (hasP) {
    const cues = parseSrv3();
    if (cues.length > 0) return cues;
  }

  if (hasText) {
    const cues = parseTranscript();
    if (cues.length > 0) return cues;
  }

  return [];
}

export async function getAvailableTracks(videoId: string): Promise<YouTubeSubtitleTrack[]> {
  const tracks = await getCaptionTracks(videoId);
  const deduped = new Map<string, YouTubeSubtitleTrack>();

  for (const track of tracks) {
    const key = `${track.languageCode}::${track.isAutoGenerated ? 'auto' : 'manual'}`;
    if (deduped.has(key)) continue;

    deduped.set(key, {
      languageCode: track.languageCode,
      name: track.name,
      isAutoGenerated: track.isAutoGenerated,
    });
  }

  return [...deduped.values()];
}

export async function fetchSubtitles(
  videoId: string,
  lang: string,
  options?: { additionalParams?: string }
): Promise<Cue[]> {
  const tracks = await getCaptionTracks(videoId);
  const selected = pickCaptionTrack(tracks, lang);
  if (!selected) {
    // Fallback: some environments block/paritize captionTracks extraction from watch HTML.
    // Try the direct timedtext endpoint which can work without track metadata.
    return fetchTimedTextFallback(videoId, lang, options);
  }

  const url = new URL(selected.baseUrl);
  applyAdditionalParams(url, options?.additionalParams);
  if (!url.searchParams.has('fmt')) url.searchParams.set('fmt', 'json3');

  const response = await fetch(url.toString(), {
    method: 'GET',
    headers: { Accept: 'application/json,text/xml,*/*' },
  });

  if (!response.ok) {
    throw new Error(`YouTube timedtext fetch failed: HTTP ${response.status} ${response.statusText}`);
  }

  const contentType = response.headers.get('content-type') ?? '';
  const bodyText = await response.text();
  const isJson =
    contentType.includes('application/json') ||
    bodyText.trim().startsWith('{') ||
    bodyText.trim().startsWith('[');

  if (isJson) {
    let json: unknown;
    try {
      json = JSON.parse(bodyText) as unknown;
    } catch {
      return fetchTimedTextFallback(videoId, lang, options);
    }
    return youtubeTimedTextToCues(json, { videoId, lang: selected.languageCode });
  }

  return youtubeTimedTextToCues(bodyText, { videoId, lang: selected.languageCode });
}

function applyAdditionalParams(url: URL, additionalParams: string | undefined): void {
  if (!additionalParams || !additionalParams.trim()) return;
  const existingKeys = new Set(url.searchParams.keys());
  const extra = new URLSearchParams(additionalParams);
  for (const [key, value] of extra.entries()) {
    if (existingKeys.has(key)) continue;
    url.searchParams.set(key, value);
  }
}

async function fetchTimedTextFallback(
  videoId: string,
  lang: string,
  options?: { additionalParams?: string }
): Promise<Cue[]> {
  const base = new URL('https://www.youtube.com/api/timedtext');
  base.searchParams.set('v', videoId);
  base.searchParams.set('lang', lang);
  applyAdditionalParams(base, options?.additionalParams);
  if (!base.searchParams.has('fmt')) base.searchParams.set('fmt', 'json3');

  const tryFetch = async (url: URL): Promise<Cue[]> => {
    const response = await fetch(url.toString(), {
      method: 'GET',
      headers: { Accept: 'application/json,text/xml,*/*' },
    });
    if (!response.ok) return [];

    const contentType = response.headers.get('content-type') ?? '';
    const bodyText = await response.text();
    const trimmed = bodyText.trim();
    if (!trimmed) return [];

    const isJson =
      contentType.includes('application/json') ||
      trimmed.startsWith('{') ||
      trimmed.startsWith('[');

    if (isJson) {
      try {
        return youtubeTimedTextToCues(JSON.parse(trimmed) as unknown, { videoId, lang });
      } catch {
        return [];
      }
    }

    return youtubeTimedTextToCues(bodyText, { videoId, lang });
  };

  // 1) Regular captions (manual or auto)
  const cues = await tryFetch(base);
  if (cues.length > 0) return cues;

  // 2) Auto-generated captions fallback (ASR)
  const asr = new URL(base);
  asr.searchParams.set('kind', 'asr');
  return tryFetch(asr);
}

export class YouTubeAdapter {
  /**
   * Get available subtitle tracks for a video.
   */
  async getAvailableTracks(videoId: string): Promise<YouTubeSubtitleTrack[]> {
    return getAvailableTracks(videoId);
  }

  /**
   * Fetch subtitles for a specific track.
   */
  async fetchSubtitles(videoId: string, languageCode: string): Promise<Cue[]> {
    return fetchSubtitles(videoId, languageCode);
  }
}
